version: '3.8'

services:
  storage:
    image: postgres:16-alpine
    container_name: log_db_storage
    environment:
      POSTGRES_DB: log_db
      POSTGRES_USER: log_user
      POSTGRES_PASSWORD: log_password
    volumes:
      - pg_data:/var/lib/postgresql/data # Persistensi data (T6, T10)
    networks:
      - pubsub_net
    restart: always

  aggregator:
    build: .
    container_name: log_aggregator
    depends_on:
      - storage # Menunggu PostgreSQL siap
    environment:
      # Database Connection String
      DATABASE_URL: postgresql://log_user:log_password@storage:5432/log_db
      MIN_CONSUMERS: "5" # Set jumlah consumer worker (T9: Uji Konkurensi)
    ports:
      - "8080:8080"
    networks:
      - pubsub_net
    restart: always
    working_dir: /app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]

  publisher:
    build: .
    container_name: log_publisher
    depends_on:
      - aggregator
    networks:
      - pubsub_net
    environment:
      # Parameter stress test (T6, T7)
      NUM_EVENTS: "25000"
      DUPLICATE_RATE: "0.35"
      AGGREGATOR_URL: "http://aggregator:8080/publish"
    # Command: Wajib menunggu Aggregator siap, lalu menjalankan publisher.
    command: ["python", "-c", "import asyncio; import os; os.environ['NUM_EVENTS'] = os.getenv('NUM_EVENTS', '25000'); os.environ['DUPLICATE_RATE'] = os.getenv('DUPLICATE_RATE', '0.35'); print('Waiting 10s for aggregator...'); asyncio.run(asyncio.sleep(10)); import src.publisher_sender; asyncio.run(src.publisher_sender.send_events())"]
    restart: "no" # Agar selesai setelah tes

networks:
  pubsub_net:
    driver: bridge

volumes:
  pg_data: # Definisi Named Volume